<?php

namespace taxi\MainBundle\Repository;

/**
 * PackCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
